import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generatePatientActionsPDF = (data, fromDate, toDate) => {
  const doc = new jsPDF("l", "mm", "a4"); // Changed to landscape mode
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  // Calculate statistics
  const totalPatients = data.length;
  const totalBeds = data.filter(p => p.bed_number && p.bed_number !== 'N/A').length;
  const ages = data.map(p => parseInt(p.age)).filter(age => !isNaN(age));
  const avgAge = ages.length > 0 ? Math.round(ages.reduce((a, b) => a + b, 0) / ages.length) : 0;
  const minAge = ages.length > 0 ? Math.min(...ages) : 0;
  const maxAge = ages.length > 0 ? Math.max(...ages) : 0;
  
  const addHeader = (pageNum) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text("LORDS DIAGNOSTIC", pageWidth / 2, 15, { align: "center" });
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text("13/3, CIRCULAR 2ND BYE LANE,", pageWidth / 2, 20, { align: "center" });
    
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 0, 0);
    doc.setFontSize(11);
    doc.text("Manager Activity", pageWidth / 2, 30, { align: "center" });
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(9);
    doc.text(`Date : ${fromDate}`, 15, 40);
    doc.text(`To : ${toDate}`, 80, 40);
  };
  
  addHeader(1);
  

  
  // Table with proper column widths
  const tableData = data.map(patient => [
    patient.admin_action_no || '',
    patient.patient_name || '',
    patient.age || '',
    patient.phone || '',
    patient.bed_number || 'N/A',
    new Date(patient.created_at).toLocaleDateString('en-GB'),
    patient.case_details || ''
  ]);
  
  autoTable(doc, {
    head: [['ID', 'Patient Name', 'Age', 'Phone', 'Bed', 'Date', 'Case Details']],
    body: tableData,
    startY: 50,
    theme: 'striped',
    headStyles: {
      fillColor: [100, 100, 255],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 10,
      halign: 'center'
    },
    bodyStyles: {
      fontSize: 9,
      cellPadding: 3
    },
    columnStyles: {
      0: { cellWidth: 20, halign: 'center' },
      1: { cellWidth: 40, halign: 'left' },
      2: { cellWidth: 20, halign: 'center' },
      3: { cellWidth: 30, halign: 'center' },
      4: { cellWidth: 20, halign: 'center' },
      5: { cellWidth: 25, halign: 'center' },
      6: { cellWidth: 120, halign: 'left' }
    },
    alternateRowStyles: {
      fillColor: [245, 245, 255]
    },
    margin: { left: 10, right: 10 },
    showHead: 'everyPage',
    didDrawPage: function (data) {
      // Footer on every page
      doc.setFontSize(8);
      doc.setTextColor(100, 100, 100);
      doc.text('Generated by Lords Healthcare Management System', 20, pageHeight - 15);
      doc.text(`Page ${data.pageNumber} of ${doc.internal.getNumberOfPages()}`, pageWidth - 40, pageHeight - 15);
    }
  });
  
  return doc;
};